version: '3'
services:
  node:
    image: node:8
    build: .
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    command: npm run start
  truffle:
    image: node:8
    working_dir: /src
    ports:
      - "9545:9545"
    command: bash /bin/docker-truffle.sh
